### ISSUE TITLE
Self Details Page

### ISSUE THREAD

**Issue by nimesh7283** [biunce/YDS-Resume#2]
There is error occurred when we complete the page of resume upload. I have attached the error for your reference.
![selfdetailspageerror](https://cloud.githubusercontent.com/assets/12139726/7352126/605cfebc-ed27-11e4-843b-6bdc78d763da.JPG)

**Comment by biunce** [comment]
This is because the older version of word doc cant be read by the system and hence giving some error. Would request you to upload the doc resume created with docx on newer version of office.. TIll there is a solution available.

**Comment by nimesh7283** [comment]
I have attached the error which comes after uploading the resume.
![resume upload error_050515](https://cloud.githubusercontent.com/assets/12139726/7475252/0e7e82f8-f364-11e4-978c-533ddfc92a6f.jpg)

**Comment by biunce** [comment]
Resolved, please check and verify it again.

**Comment by nimesh7283** [comment]
Resume upload page is successfully saved but not able view resume on profile page.

**Comment by biunce** [comment]
Done

**Comment by nimesh7283** [comment]
Give a link for resume download

**Comment by biunce** [comment]
done. added in the view profiles page
