### ISSUE TITLE
Job Posting Approval on Admin Login

### ISSUE THREAD

**Issue by nimesh7283** [biunce/YDS-Resume#3]
There is an error after approving the job posting on the admin login.
![jobpostingapproveerr](https://cloud.githubusercontent.com/assets/12139726/7352207/e13b886e-ed27-11e4-8107-9641d704292b.JPG)

**Comment by biunce** [comment]
Done, please check and re-check it if its occuring

**Comment by nimesh7283** [comment]
The above error is resolved in Admin ID but when we see and click on the user id, then it shows the error. I have attached for your reference.
![job opening error](https://cloud.githubusercontent.com/assets/12139726/7474931/3ae6636c-f362-11e4-9753-38d848154f05.jpg)

**Comment by biunce** [comment]
May you Please check this. I am not getting any error on this please.

**Comment by nimesh7283** [comment]
done
